config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :agences

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/acquereur.rb
class Acquereur < ActiveRecord::Base
  belongs_to :user
  belongs_to :agence
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agence.rb
class Agence < ActiveRecord::Base
  has_many :users
  has_many :acquereurs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  belongs_to :agence
  has_many :acquereurs
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/agences_controller.rb
class AgencesController < ApplicationController
  before_action :set_agence, only: [:show, :edit, :update, :destroy]

  # GET /agences
  # GET /agences.json
  def index
    @agences = Agence.all
  end

  # GET /agences/1
  # GET /agences/1.json
  def show
  end

  # GET /agences/new
  def new
    @agence = Agence.new
  end

  # GET /agences/1/edit
  def edit
  end

  # POST /agences
  # POST /agences.json
  def create
    @agence = Agence.new(agence_params)

    respond_to do |format|
      if @agence.save
        format.html { redirect_to @agence, notice: 'Agence was successfully created.' }
        format.json { render :show, status: :created, location: @agence }
      else
        format.html { render :new }
        format.json { render json: @agence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agences/1
  # PATCH/PUT /agences/1.json
  def update
    respond_to do |format|
      if @agence.update(agence_params)
        format.html { redirect_to @agence, notice: 'Agence was successfully updated.' }
        format.json { render :show, status: :ok, location: @agence }
      else
        format.html { render :edit }
        format.json { render json: @agence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agences/1
  # DELETE /agences/1.json
  def destroy
    @agence.destroy
    respond_to do |format|
      format.html { redirect_to agences_url, notice: 'Agence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agence
      @agence = Agence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agence_params
      params.require(:agence).permit(:nom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/agences_helper.rb
module AgencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/agences/_form.html.erb
<%= form_for @agence, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nom, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nom, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  agences_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/agences/edit.html.erb
<%- model_class = Agence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Agence %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agences/index.html.erb
<%- model_class = Agence -%>
<div class="page-header">
  <h1><%=t '.title', :default => Agence %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @agences.each do |agence| %>
      <tr>
        <td><%= agence.id %></td>
        <td><%= agence.nom %></td>
        <td><%=l agence.created_at, format: :long %></td>
        <td>
          <%= link_to agence_path(agence), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to agence_path(agence), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_agence_path,
            :class => 'btn btn-primary' %>

app/views/agences/new.html.erb
<%- model_class = Agence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Agence %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agences/show.html.erb
<%- model_class = Agence -%>
<div class="page-header">
  <h1><%=t '.title', :default => Agence %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nom) %></dt>
      <dd><pre class="prettyprint"><%= @agence.nom %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              agences_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_agence_path(@agence), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              agence_path(@agence),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demomori</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>